[package]
name = "caption-compiler"
version = "0.2.0"
authors = ["Kara <https://github.com/Karalynx>"]
description = "Compiles and describes Valve's closed caption files"
readme = "README.md"
edition = "2024"
keywords = ["valve", "source-engine", "closed-captions", "cli"]
categories = ["command-line-utilities", "game-development"]
repository = "https://github.com/Karalynx/caption-compiler"
license = "GPL-3.0"
exclude = [
	".gitignore",
	".github/*",
	"flake.*",
	".envrc"
]

[dependencies]
clap = { version = "4.6.1", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }
crc32fast = "1.5.0"
encoding_rs = "0.8.35"
packbytes = "0.2.0"
